### ISSUE TITLE
How to batch queries

### ISSUE THREAD

**Issue by bohutang** [vorot93/ethereum-jsonrpc#1]
Hi,

Nice project!
With `ethereum-jsonrpc`, how to do batch RPC queries like https://docs.rs/web3/latest/web3/transports/batch/struct.Batch.html?
Codes:
https://github.com/tomusdrw/rust-web3/blob/master/src/transports/batch.rs

`jsonrpsee` supports `batch_request` and the demo: https://github.com/paritytech/jsonrpsee/blob/e6c6ac58a182930f7aaf304395b2eb664c7eecc5/client/http-client/src/tests.rs#L139-L146
This is very useful and efficient when fetching huge data from the Ethereum node batch instead of one by one.

**Comment by niklasad1** [comment]
https://github.com/paritytech/jsonrpsee/blob/master/tests/tests/integration_tests.rs#L562-#L577

The same API is implemented by [http client as well](https://docs.rs/jsonrpsee-http-client/0.15.1/jsonrpsee_http_client/struct.HttpClient.html#impl-ClientT-for-HttpClient)

however, you can't use `rpc macro API` for batches see https://github.com/paritytech/jsonrpsee/issues/688 so must call the methods "manually" yourself.
